"""Noise — a white or pink noise generator (audio + CV source).

A random-signal source with no inputs and two output jacks carrying
the *same* noise stream: an ``out`` (audio) jack to drive filters and
speakers directly (snares, hats, wind, breath), and a ``cv`` jack to
drive modulation directly (the textbook random-voltage source — patch
it into :class:`SampleHold`'s ``in`` for stepped random pitches). Two
jacks rather than one bridge: noise is equally at home as audio or as
control, so it's offered as both, the way Keyboard exposes ``out`` and
``gate``.

Colors (param ``color``):
  * ``white`` (default) — flat power across the spectrum; uniform
    ``[-1, 1]`` per sample. Bright, hissy; the raw material for hats
    and the classic S&H source.
  * ``pink`` — equal power *per octave* (−3 dB/oct), the spectral
    tilt of rushing water, rain, and most natural noise. Generated by
    filtering white through a 3rd-order pinking IIR
    (``scipy.signal.lfilter``, filter state carried across blocks for
    spectral continuity), then RMS-normalised so it sits at the same
    level as white at a given ``amp``. Darker, smoother; gentler as a
    modulation source.

Param ``amp`` (default 1.0) scales both outputs. White is hard-bounded
to ``±amp``; pink is RMS-matched to white, so its occasional peaks run
a little past ``±amp`` (normal for filtered noise — the speaker limiter
handles the audio path, and CV destinations are scaled to taste with
:class:`CVScale`/:class:`CVOffset`).

Output is always mono ``(frames,)`` — a source has no voice context of
its own (like :class:`Constant`), and a 1D signal broadcasts cleanly
against any per-voice consumer downstream.
"""
from __future__ import annotations

from ..core.module import Module, register_module_type
from ..core.port import Port


NOISE_COLORS = ("white", "pink")


@register_module_type
class Noise(Module):
    """White / pink noise source. No inputs; ``out`` (audio) + ``cv`` (cv).

    Parameters:
        color: ``"white"`` (flat) or ``"pink"`` (−3 dB/oct). Default
            ``"white"``.
        amp: Linear level applied to both outputs. Default 1.0.

    Ports:
        out (out, audio): the noise as audio.
        cv (out, cv): the same noise as control voltage.
    """

    TYPE = "noise"
    DEFAULT_PARAMS = {"color": "white", "amp": 1.0}
    INPUT_PORTS: list[Port] = []
    OUTPUT_PORTS = [
        Port("out", "out", "audio"),
        Port("cv", "out", "cv"),
    ]
